### ISSUE TITLE
Swift project build failed after pod install

### ISSUE THREAD

**Issue by springlo** [zoloz-pte-ltd/zoloz-demo-ios#1]
<img width="814" alt="image" src="https://github.com/zoloz-pte-ltd/zoloz-demo-ios/assets/373580/23ef8a5a-7b39-45e0-b640-a2c6279d4e6f">

**Comment by cundytvlk** [comment]
Hi @springlo , I encountered the same issue with the latest version (1.3.7.240326162645) . Do you happen to be able to find the workaround for this?

**Comment by hinovo** [comment]
try add `“-ld_classic”` in Other LInker Flags @springlo @cundytvlk

**Comment by cundytvlk** [comment]
hi @hinovo , I've tried adding `“-ld_classic”` and now it still return build failed with following error:
I'm using Xcode 15.2 and building to device
<img width="819" alt="Screenshot 2024-05-07 at 13 26 11" src="https://github.com/zoloz-pte-ltd/zoloz-demo-ios/assets/104339471/dace646b-6b51-4a34-9e85-2e62057b609d">

Update:
The issue is resolved after I update to latest version 1.3.7.240326162645 (was experimenting to downgrade the version before)
